prep for work on calc version 3.0.1.0
    **NOTE**: At the start of calc version 3.0.1.0, the code identical to calc version 2.17.0.0,
              except for the version number of course.  :-)  Nevertheless, because the
              `MAJOR_VER` changed from from 2 to 3, code in `int.h`, `value.h`, and `zmath.h`
              will compile differently due to C pre-processor directives related to the
              `MAJOR_VER` defined symbol.  In particular, the memory layout of fundamental
              data types such as `VALUE` (`struct value`), `LEN`, `SIGN`, and `ZVALUE`
              have a different memory layout.

    **TL;DR**: The calc version 3.0.1.0 == calc version 2.17.0.0, except for the version number.
               The change of version number causes a change in memory layout of data structures.

    Change `MAJOR_VER` from 2 to 3, the first change to the major version number since 1989!

The following are the changes from calc version 2.17.0.0 to 3.0.1.0:

    **NOTE**: This is the restart of the calcv3 branch for calc version 3 development:

        https://github.com/lcn2/calc/issues/103

    As calc version 3.0.0.4, with the version set to new 2.17.0.0, was folded into the
    master bench, this calc 3.0.1.0 version may be considered the re-start of calc v3.

    With respect to calc version 3.0.0.4 vs calc version 3.0.1.0 contains several Makefile
    fixes and improvements, an rpm spec change, and `make clang-format` source format to update.
    In the next change section "changes from calc version 2.16.1.3 to 2.17.0.0" until the
    "From: calc version 3.0.0.3 to 3.0.0.4 changes" line, you will find the details of
    the calc version 3.0.0.4 vs calc version 3.0.1.0 change.

diff --git a/chk_tree b/chk_tree
--- a/chk_tree
+++ b/chk_tree
@@ -4,7 +4,7 @@
 #
 # This tools is used by "make prep", "make full_debug", and "make debug".
 #
-# Copyright (C) 2023 Landon Curt Noll
+# Copyright (C) 2023,2026 Landon Curt Noll
 #
 # Calc is open software; you can redistribute it and/or modify it under
 # the terms of version 2.1 of the GNU Lesser General Public License
@@ -193,7 +193,8 @@ declare -a FINDDIR
 mapfile -t FINDDIR < <(find . -type d \
         ! -path './NOTES/*' ! -name NOTES \
         ! -path './.git/*' ! -name .git \
-        ! -path './.github/*' ! -name .github | \
+        ! -path './.github/*' ! -name .github \
+        ! -name picky ! -path './picky/*' | \
         sed -e 's/^\.\///' | sort -u)
 if [[ ${#FINDDIR[@]} -le 0 ]]; then
     echo "$0: ERROR: find dir is empty" 1>&2
@@ -278,12 +279,12 @@ if [[ -d .git ]]; then
 
         # report that DISTLIST and GITLS differ
         #
-        echo "$0: ERROR: distlist and git ls differ for critical files" 1>&2
+        echo "$0: ERROR: distlist and git ls-tree -r --name-only HEAD differ for critical files" 1>&2
         declare -a ONLY_GITLS
         mapfile -t ONLY_GITLS < <(printf '%s\n' "${DISTLIST[@]}" "${DISTLIST[@]}" "${GITLS[@]}" |
                                   tr ' ' '\n' | sort | uniq -u)
         if [[ ${#ONLY_GITLS[@]} -ne 0 ]]; then
-            echo "$0: ERROR: found only in git ls: ${ONLY_GITLS[*]}" 1>&2
+            echo "$0: ERROR: found only in git ls-tree -r --name-only HEAD: ${ONLY_GITLS[*]}" 1>&2
         fi
         declare -a ONLY_DISTLIST
         mapfile -t ONLY_DISTLIST < <(printf '%s\n' "${GITLS[@]}" "${GITLS[@]}" "${DISTLIST[@]}" |
@@ -421,6 +422,7 @@ mapfile -t FINDFILE < <(find . -type f \
         ! -name 'CODE_OF_CONDUCT.md' ! -name 'CONTRIBUTING.md' ! -name '.gitignore' ! -name 'SECURITY.md'  \
         ! -name '*.swp' ! -name '?' ! -iname '*.out*' \
         ! -iname '*foo*' ! -iname '*bar*' ! -iname '*baz*' \
+        ! -name 'picky' ! -path './picky/*' \
         ! -iname '*curds*' ! -iname '*whey*' ! -iname '*rmmee' -print |
         sed -e 's/^\.\///' | sort -u)
 if [[ ${#FINDFILE[@]} -le 0 ]]; then
