sync with calv2, expand tabs in len_bits.h and errsym.h
Import documentation changes from the calcv2 branch in regards to
the "XDG base dir. spec. adoption", update to the `trailblank` tool
to ignore in `calc.man`, `help/environment`, and `README.md`.

Added `${EXPAND}` to the list of utilities in `Makefile.config`.
Echo `${EXPAND}` in the `make env` rule of `Makefile`.

Use `${EXPAND}` to replace ASCII tabs with ASCII spaces in the
`make len_bits.h` rule, and the `make errsym.h` rule of `Makefile`.

diff --git a/chk_tree b/chk_tree
--- a/chk_tree
+++ b/chk_tree
@@ -60,15 +60,15 @@ export USAGE="usage: $0 [-h] [-v level] [-V] [-d topdir] [-m]
     -v level    set verbosity level (def level: $V_FLAG)
     -V          print version string and exit
 
-    -m		used by make full_debug or make debug (def: run by hand)
+    -m          used by make full_debug or make debug (def: run by hand)
 
-    -d topdir	set topdir (def: $TOPDIR)
+    -d topdir   set topdir (def: $TOPDIR)
 
 Exit codes:
      0         all OK
      2         -h and help string printed or -V and version string printed
      3         command line error
-     5	       some internal tool is not found or not an executable file
+     5         some internal tool is not found or not an executable file
      6         problems found with or in the topdir
  >= 10         internal error
 
@@ -80,32 +80,32 @@ $NAME version: $VERSION"
 while getopts :hv:Vd:m flag; do
   case "$flag" in
     h) echo "$USAGE"
-	exit 2
-	;;
+        exit 2
+        ;;
     v) V_FLAG="$OPTARG"
-	;;
+        ;;
     V) echo "$VERSION"
-	exit 2
-	;;
+        exit 2
+        ;;
     d) TOPDIR="$OPTARG"
         ;;
     m) M_FLAG="true"
-	;;
+        ;;
     \?) echo "$0: ERROR: invalid option: -$OPTARG" 1>&2
-	echo 1>&2
-	echo "$USAGE" 1>&2
-	exit 3
-	;;
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
     :) echo "$0: ERROR: option -$OPTARG requires an argument" 1>&2
-	echo 1>&2
-	echo "$USAGE" 1>&2
-	exit 3
-	;;
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
     *) echo "$0: ERROR: unexpected value from getopts: $flag" 1>&2
-	echo 1>&2
-	echo "$USAGE" 1>&2
-	exit 3
-	;;
+        echo 1>&2
+        echo "$USAGE" 1>&2
+        exit 3
+        ;;
   esac
 done
 if [[ $V_FLAG -ge 1 ]]; then
@@ -318,14 +318,14 @@ if [[ -d .git ]]; then
     #
     GIT_BRANCH=$(git branch --show-current 2<&1)
     if [[ -z $GIT_BRANCH ]]; then
-	echo "$0: ERROR: cannot determine current branch" 1>&2
-	git --no-pager branch --list
+        echo "$0: ERROR: cannot determine current branch" 1>&2
+        git --no-pager branch --list
         EXIT_CODE=20
         echo "$0: Warning: set EXIT_CODE: $EXIT_CODE" 1>&2
     fi
     GIT_BRANCH=${GIT_BRANCH:="master"}
     if [[ -z $M_FLAG && $GIT_BRANCH != master ]]; then
-	echo "$0: ERROR: not on master branch and -m was not used" 1>&2
+        echo "$0: ERROR: not on master branch and -m was not used" 1>&2
         EXIT_CODE=21
         echo "$0: Warning: set EXIT_CODE: $EXIT_CODE" 1>&2
     fi
@@ -333,10 +333,10 @@ if [[ -d .git ]]; then
     # output branch info if -m
     #
     if [[ -n $M_FLAG ]]; then
-	echo "$0: on branch: $GIT_BRANCH" 1>&2
-	echo "$0: git branch starts below" 1>&2
-	git --no-pager branch
-	echo "$0: git branch ends above" 1>&2
+        echo "$0: on branch: $GIT_BRANCH" 1>&2
+        echo "$0: git branch starts below" 1>&2
+        git --no-pager branch
+        echo "$0: git branch ends above" 1>&2
     fi
 
     # verify that current branch is not ahead of 'origin/branch'
@@ -358,9 +358,9 @@ if [[ -d .git ]]; then
     # output status if -m
     #
     if [[ -n $M_FLAG ]]; then
-	echo "$0: git status starts below" 1>&2
-	git --no-pager status
-	echo "$0: git status ends above" 1>&2
+        echo "$0: git status starts below" 1>&2
+        git --no-pager status
+        echo "$0: git status ends above" 1>&2
     fi
 fi
 
diff --git a/trailblank b/trailblank
--- a/trailblank
+++ b/trailblank
@@ -33,7 +33,7 @@
 #
 export EXIT_CODE=0
 
-# Look for leading whiitespace before a tab
+# Look for leading whitespace before a tab
 #
 # We exclude binary files, RCS source code history, intermediate
 # compiled files, patch droppings and compiled binary libraries.
@@ -56,13 +56,14 @@ LEADING_SPACES_BEFORE_TAB=$(
               -name '*.ptch' -o -name 'core.*' -o \
               -name '*.so*' -o -name 'calc-static' -o -name 'libcalc.*' -o \
               -name 'sample_many' -o -name 'sample_rand' -o -name 'errcode' -o \
-              -path './help/funclist' -o \
+              -path './help/funclist' -o -path './have_stdvs' -o \
               -path './endian' -o -path './no_implicit' -o -name 'chk_c' -o \
               -path './longbits' -o -name '.*.swp' -o -name 'conf.h' -o \
               -name '.git' -o -path './custom/libcustcalc*' -o -path './libcustcalc*' -o \
               -name 'sample_many-static' -o -name 'sample_rand-static' -o \
-              -name 'codeql-analysis.yml' -o -name tags -o -name '*.out' -o \
+              -name 'codeql.yml' -o -name 'test.yml' -o -name tags -o -name '*.out' -o \
               -name '?' -o -iname '*foo*' -o -iname '*bar*' -o -iname '*baz*' -o \
+              -name 'picky' -o -path './picky/*' -o \
               -iname '*curds*' -o -iname '*whey*' -o -iname '*rmme*' \
            \) -prune -o -type f -print0 | \
     xargs -0 egrep -l '^        *  *    '
@@ -97,12 +98,13 @@ TRAILING_WHITESPACE=$(
               -name '*.ptch' -o -name 'core.*' -o \
               -name '*.so*' -o -name 'calc-static' -o -name 'libcalc.*' -o \
               -name 'sample_many' -o -name 'sample_rand' -o -name 'errcode' -o \
-              -path './help/funclist' -o \
+              -path './help/funclist' -o -path './have_stdvs' -o \
               -path './endian' -o -path './no_implicit' -o -name 'chk_c' -o \
               -path './longbits' -o -name '.*.swp' -o -name 'conf.h' -o \
               -name '.git' -o -path './custom/libcustcalc*' -o -path './libcustcalc*' -o \
               -name 'sample_many-static' -o -name 'sample_rand-static' -o \
               -name '?' -o -iname '*foo*' -o -iname '*bar*' -o -iname '*baz*' -o \
+              -name 'picky' -o -path './picky/*' -o \
               -iname '*curds*' -o -iname '*whey*' -o -iname '*rmme*' \
            \) -prune -o -type f -print0 | \
     xargs -0 egrep -l '[         ]$'
@@ -166,6 +168,12 @@ fi
 #
 # Such files are temporary/test files and are not part of calc.
 #
+# We also ignore in phase 1:
+#
+#       calc.man help/environment README.md
+#
+# Those files will be processed in phase 2 because they contain long lines.
+#
 # Last, we have files that have long lines that, for now,
 # we cannot be as picky about without significant work.
 #
@@ -176,14 +184,16 @@ PICKY_PHASE_1=$(
               -name '*.ptch' -o -name 'core.*' -o \
               -name '*.so*' -o -name 'calc-static' -o -name 'libcalc.*' -o \
               -name 'sample_many' -o -name 'sample_rand' -o -name 'errcode' -o \
-              -path './help/funclist' -o \
+              -path './help/funclist' -o -path './have_stdvs' -o \
               -path './endian' -o -path './no_implicit' -o -name 'chk_c' -o \
               -path './longbits' -o -name '.*.swp' -o -name 'conf.h' -o \
               -name '.git' -o -path './custom/libcustcalc*' -o -path './libcustcalc*' -o \
               -name 'sample_many-static' -o -name 'sample_rand-static' -o \
-              -name 'codeql-analysis.yml' -o -name tags -o -name '*.out' -o \
+              -name 'codeql.yml' -o -name 'test.yml' -o -name tags -o -name '*.out' -o \
               -iname '*foo*' -o -iname '*bar*' -o -iname '*baz*' -o \
-              -name '.lldbinit' -o -iname '*curds*' -o -iname '*whey*' -o -iname '*rmme*' \
+              -name 'picky' -o -path './picky/*' -o \
+              -name '.lldbinit' -o -iname '*curds*' -o -iname '*whey*' -o -iname '*rmme*' -o \
+              -name 'calc.man' -o -path './help/environment' -o -name 'README.md' \
            \) -prune -o -type f -print0 | \
     if [[ -x /usr/local/bin/picky ]]; then
         xargs -0 /usr/local/bin/picky -s -v -w132
@@ -198,9 +208,36 @@ PICKY_PHASE_1=$(
 )
 if [[ -n $PICKY_PHASE_1 ]]; then
     echo
-    echo '# files flagged by picky'
+    echo '# files flagged by picky phase 1'
     echo "$PICKY_PHASE_1" | sed -e 's/^picky: \.\///' -e 's/ / - /'
     EXIT_CODE=6
+fi
+
+# Picky tool processing phase 2
+#
+# We process:
+#
+#       calc.man help/environment README.md
+#
+# except we use -w0 to ignore line lengths.
+#
+PICKY_PHASE_2=$(
+    if [[ -x /usr/local/bin/picky ]]; then
+        /usr/local/bin/picky -s -v -w0 calc.man help/environment README.md
+    else
+        echo "# $0: WARNING: /usr/local/bin/picky not found: skipping picky phase 2 check!" 1>&2
+        echo "#" 1>&2
+        echo "# $0: NOTICE: The picky tool used is from the following GitHub repo:" 1>&2
+        echo "#" 1>&2
+        echo "#         https://github.com/lcn2/picky for the picky tool GitHub repo." 1>&2
+        echo "#" 1>&2
+    fi
+)
+if [[ -n $PICKY_PHASE_2 ]]; then
+    echo
+    echo '# files flagged by picky phase 2'
+    echo "$PICKY_PHASE_2" | sed -e 's/^picky: \.\///' -e 's/ / - /'
+    EXIT_CODE=7
 fi
 
 # look for backup Makefiles
@@ -215,7 +252,7 @@ if [[ -n $BACKUP_MAKEILES ]]; then
     echo "$BACKUP_MAKEILES" | while read -r file; do
         echo "rm -f $file"
     done
-    EXIT_CODE=7
+    EXIT_CODE=8
 fi
 
 
@@ -228,13 +265,14 @@ TABS_FOUND=$(
               -name '*.ptch' -o -name 'core.*' -o \
               -name '*.so*' -o -name 'calc-static' -o -name 'libcalc.*' -o \
               -name 'sample_many' -o -name 'sample_rand' -o -name 'errcode' -o \
-              -path './help/funclist' -o \
+              -path './help/funclist' -o -path './have_stdvs' -o \
               -path './endian' -o -path './no_implicit' -o -name 'chk_c' -o \
               -path './longbits' -o -name '.*.swp' -o -name 'conf.h' -o \
               -name '.git' -o -path './custom/libcustcalc*' -o -path './libcustcalc*' -o \
               -name 'sample_many-static' -o -name 'sample_rand-static' -o \
-              -name 'codeql-analysis.yml' -o -name tags -o -name '*.out' -o \
+              -name 'codeql.yml' -o -name tags -o -name '*.out' -o \
               -iname '*foo*' -o -iname '*bar*' -o -iname '*baz*' -o \
+              -name 'picky' -o -path './picky/*' -o \
               -name '.lldbinit' -o -iname '*curds*' -o -iname '*whey*' -o -iname '*rmme*' -o \
               -iname 'Makefile*' -o -name rpm.mk -o -name 'trailblank' \
            \) -prune -o -type f -print0 | \
@@ -244,7 +282,7 @@ if [[ -n $TABS_FOUND ]]; then
     echo
     echo '# ASCII TABs found in non-Makefiles:'
     echo "$TABS_FOUND"
-    EXIT_CODE=8
+    EXIT_CODE=9
 fi
 
 # All Done!!! -- Jessica Noll, Age 2
