fix GitHub actions
Use `git ls-tree -r --name-only HEAD` instead of `git ls` alias.

Skip checks of any picky installation tree.

diff --git a/chk_tree b/chk_tree
--- a/chk_tree
+++ b/chk_tree
@@ -61,7 +61,8 @@ declare -a FINDDIR
 mapfile -t FINDDIR < <(find . -type d \
         ! -path './NOTES/*' ! -name NOTES \
         ! -path './.git/*' ! -name .git \
-        ! -path './.github/*' ! -name .github | \
+        ! -path './.github/*' ! -name .github \
+        ! -name picky ! -path './picky/*' | \
         sed -e 's/^\.\///' | sort -u)
 if [[ ${#FINDDIR[@]} -le 0 ]]; then
     echo "$0: ERROR: find dir is empty" 1>&2
@@ -128,11 +129,11 @@ if [[ -d .git ]]; then
     # We ignore .git and GitHub related files because they are not part of the calc source tarball.
     #
     declare -a GITLS
-    mapfile -t GITLS < <(git ls |
+    mapfile -t GITLS < <(git ls-tree -r --name-only HEAD |
         grep -v -E '^\.github/|^\.gitignore$|^CODE_OF_CONDUCT\.md$|^CONTRIBUTING\.md$|^SECURITY\.md$' |
         sort -u)
     if [[ ${#GITLS[@]} -le 0 ]]; then
-        echo "$0: ERROR: git ls is empty" 1>&2
+        echo "$0: ERROR: git ls-tree -r --name-only HEAD is empty" 1>&2
         EXIT_CODE=16
         echo "$0: Warning: set EXIT_CODE: $EXIT_CODE" 1>&2
     fi
@@ -146,12 +147,12 @@ if [[ -d .git ]]; then
 
         # report that DISTLIST and GITLS differ
         #
-        echo "$0: ERROR: distlist and git ls differ for critical files" 1>&2
+        echo "$0: ERROR: distlist and git ls-tree -r --name-only HEAD differ for critical files" 1>&2
         declare -a ONLY_GITLS
         mapfile -t ONLY_GITLS < <(printf '%s\n' "${DISTLIST[@]}" "${DISTLIST[@]}" "${GITLS[@]}" |
                                   tr ' ' '\n' | sort | uniq -u)
         if [[ ${#ONLY_GITLS[@]} -ne 0 ]]; then
-            echo "$0: ERROR: found only in git ls: ${ONLY_GITLS[*]}" 1>&2
+            echo "$0: ERROR: found only in git ls-tree -r --name-only HEAD: ${ONLY_GITLS[*]}" 1>&2
         fi
         declare -a ONLY_DISTLIST
         mapfile -t ONLY_DISTLIST < <(printf '%s\n' "${GITLS[@]}" "${GITLS[@]}" "${DISTLIST[@]}" |
@@ -272,6 +273,7 @@ mapfile -t FINDFILE < <(find . -type f \
         ! -name 'CODE_OF_CONDUCT.md' ! -name 'CONTRIBUTING.md' ! -name '.gitignore' ! -name 'SECURITY.md'  \
         ! -name '*.swp' ! -name '?' ! -iname '*.out*' \
         ! -iname '*foo*' ! -iname '*bar*' ! -iname '*baz*' \
+        ! -name 'picky' ! -path './picky/*' \
         ! -iname '*curds*' ! -iname '*whey*' ! -iname '*rmmee' -print |
         sed -e 's/^\.\///' | sort -u)
 if [[ ${#FINDFILE[@]} -le 0 ]]; then
