fix make depend

diff --git a/Makefile.simple b/Makefile.simple
--- a/Makefile.simple
+++ b/Makefile.simple
@@ -3985,6 +3985,12 @@ depend: hsrc custom/Makefile
 	else \
 	    ${TRUE}; \
 	fi
+	${Q} if type -f ${MAKEDEPEND}; then \
+	    ${TRUE}; \
+	else \
+	    echo "make depend failed: cannot find makedepend command: ${MAKEDEPEND}" 1>&2; \
+	    exit 1; \
+	fi
 	${V} echo '=-=-=-=-= Invoking depend rule for cscript =-=-=-=-='
 	${Q} cd cscript; ${MAKE} -f Makefile ${CSCRIPT_PASSDOWN} depend
 	${V} echo '=-=-=-=-= Back to the main Makefile for $@ rule =-=-=-=-='
diff --git a/custom/Makefile.simple b/custom/Makefile.simple
--- a/custom/Makefile.simple
+++ b/custom/Makefile.simple
@@ -806,10 +806,16 @@ calcliblist: ${CALCLIBLIST}
 
 depend:
 	${Q} if [ -f ${MAKE_FILE}.bak ]; then \
-	    echo "custom/${MAKE_FILE}.bak exists, remove or move it"; \
+	    echo "custom/${MAKE_FILE}.bak exists, remove or move it" 1>&2; \
 	    exit 1; \
 	else \
 	    ${TRUE}; \
+	fi
+	${Q} if type -f ${MAKEDEPEND}; then \
+	    ${TRUE}; \
+	else \
+	    echo "make depend failed: cannot find makedepend command: ${MAKEDEPEND}" 1>&2; \
+	    exit 1; \
 	fi
 	${Q} echo forming custom/skel
 	${Q} ${RM} -rf skel
@@ -831,7 +837,7 @@ depend:
 	    echo '#endif /* '"$$tag"' */' >> "skel/custom/$$i"; \
 	done
 	${Q} (cd ..; ${MAKE} -f ${MAKE_FILE} hsrc)
-	${MAKE} -f ../${MAKE_FILE} h_list 2>/dev/null | \
+	(cd ..; ${MAKE} -f ${MAKE_FILE} h_list 2>/dev/null) | \
 	    while read i; do \
 		if [ ! -f "../$$i" ]; then continue; fi; \
 		tag="`echo $$i | ${SED} 's/[\.+,:]/_/g'`"; \
@@ -845,7 +851,7 @@ depend:
 	${Q} echo custom/skel formed
 	${Q} echo forming custom dependency list
 	${Q} :> skel/custom/makedep.out
-	${Q} cd skel/custom; ${MAKEDEPEND} \
+	-${Q} cd skel/custom; ${MAKEDEPEND} \
 	    -I../../.. -w 1 -f makedep.out -- \
 	    ${CFLAGS} -- \
 	    ${C_SRC} 2>/dev/null
