Release calc version 2.12.4.4

diff --git a/Makefile.simple b/Makefile.simple
--- a/Makefile.simple
+++ b/Makefile.simple
@@ -39,8 +39,8 @@
 # received a copy with calc; if not, write to Free Software Foundation, Inc.
 # 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
 #
-MAKEFILE_REV= $$Revision: 30.46 $$
-# @(#) $Id: Makefile.ship,v 30.46 2010/09/02 09:48:41 chongo Exp $
+MAKEFILE_REV= $$Revision: 30.47 $$
+# @(#) $Id: Makefile.ship,v 30.47 2011/05/23 22:47:49 chongo Exp $
 # @(#) $Source: /usr/local/src/cmd/calc/RCS/Makefile.ship,v $
 #
 # Under source code control:	1990/02/15 01:48:41
@@ -974,7 +974,7 @@ EXT=
 
 # The default calc versions
 #
-VERSION= 2.12.4.3
+VERSION= 2.12.4.4
 VERS= 2.12.4
 VER= 2.12
 VE= 2
@@ -4330,6 +4330,81 @@ strip:
 	    fi; \
 	done
 	${V} echo '=-=-=-=-= ${MAKE_FILE} end of $@ rule =-=-=-=-='
+
+# calc-symlink - setup symlinks from stardard locations into the ${T} tree
+#
+calc-symlink:
+	${Q}if [ -z "${T}" ]; then \
+	    echo "cannot use $@ make rule when T make var is empty" 1>&2; \
+	    echo "aborting" 1>&2; \
+	    exit 1; \
+	fi
+	-${Q} for i in	${BINDIR}/calc${EXT} \
+			${BINDIR}/calc-static${EXT} \
+			${SCRIPTDIR} \
+			${LIBDIR}/libcalc${LIB_EXT_VERSION} \
+			${LIBDIR}/libcustcalc${LIB_EXT_VERSION} \
+			${MANDIR}/calc.${MANEXT} \
+			${CALC_SHAREDIR} \
+			${CALC_INCDIR} \
+			; do \
+	    if [ -e "${T}$$i" ]; then \
+		    if [ "${T}$$i" -ef "$$i" ]; then \
+		    	echo "ERROR: ${T}$$i is the same as $$i" 1>&2; \
+		    else \
+			if [ -e "$$i" ]; then \
+			    echo ${RM} -f "$$i"; \
+			    ${RM} -f "$$i"; \
+			fi; \
+			echo ${LN} -s "${T}$$i" "$$i"; \
+			${LN} -s "${T}$$i" "$$i"; \
+	    	    fi; \
+	    else \
+	        echo "Warning: not found: ${T}$$i" 1>&2; \
+	    fi; \
+	done
+	-${Q} if [ -n "${CATDIR}" ]; then \
+	    if [ -e "${T}${CATDIR}/calc.${CATEXT}" ]; then \
+		if [ "${T}${CATDIR}/calc.${CATEXT}" -ef "${CATDIR}/calc.${CATEXT}" ]; then \
+		    	echo "ERROR: ${T}${CATDIR}/calc.${CATEXT} is the same as ${CATDIR}/calc.${CATEXT}" 1>&2; \
+		else \
+		    if [ -e "${CATDIR}/calc.${CATEXT}" ]; then \
+			echo ${RM} -f "${CATDIR}/calc.${CATEXT}"; \
+			${RM} -f "${CATDIR}/calc.${CATEXT}"; \
+		    fi; \
+		    echo ${LN} -s "${T}${CATDIR}/calc.${CATEXT}" "${CATDIR}/calc.${CATEXT}"; \
+		    ${LN} -s "${T}${CATDIR}/calc.${CATEXT}" "${CATDIR}/calc.${CATEXT}"; \
+		fi; \
+	    fi; \
+	fi
+
+# remove any symlinks that may have been created by calc-symlink
+#
+calc-unsymlink:
+	-${Q} for i in	${BINDIR}/calc${EXT} \
+			${BINDIR}/calc-static${EXT} \
+			${SCRIPTDIR} \
+			${LIBDIR}/libcalc${LIB_EXT_VERSION} \
+			${LIBDIR}/libcustcalc${LIB_EXT_VERSION} \
+			${MANDIR}/calc.${MANEXT} \
+			${CALC_SHAREDIR} \
+			${CALC_INCDIR} \
+			; do \
+	    if [ -L "$$i" ]; then \
+		echo ${RM} -f "$$i"; \
+		${RM} -f "$$i"; \
+	    else \
+	        echo "Warning: ignoring non-symlink: $$i" 1>&2; \
+	    fi; \
+	done
+	-${Q} if [ -n "${CATDIR}" ]; then \
+	    if [ -L "${CATDIR}/calc.${CATEXT}" ]; then \
+		echo ${RM} -f "${CATDIR}/calc.${CATEXT}"; \
+		${RM} -f "${CATDIR}/calc.${CATEXT}"; \
+	    else \
+	        echo "Warning: ignoring non-symlink: ${CATDIR}/calc.${CATEXT}" 1>&2; \
+	    fi; \
+	fi
 
 ###
 #
