Release calc version 2.12.1.3

diff --git a/cscript/Makefile b/cscript/Makefile
--- a/cscript/Makefile
+++ b/cscript/Makefile
@@ -1,7 +1,7 @@
 #
 # cscript - makefile for calc shell script files
 #
-# Copyright (C) 1999  Landon Curt Noll
+# Copyright (C) 1999-2006  Landon Curt Noll
 #
 # Calc is open software; you can redistribute it and/or modify it under
 # the terms of the version 2.1 of the GNU Lesser General Public License
@@ -17,8 +17,8 @@
 # received a copy with calc; if not, write to Free Software Foundation, Inc.
 # 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
 #
-# @(#) $Revision: 29.25 $
-# @(#) $Id: Makefile,v 29.25 2006/09/18 00:13:59 chongo Exp $
+# @(#) $Revision: 29.27 $
+# @(#) $Id: Makefile,v 29.27 2006/09/18 07:04:42 chongo Exp $
 # @(#) $Source: /usr/local/src/cmd/calc/cscript/RCS/Makefile,v $
 #
 # Under source code control:	1999/11/29 11:10:26
@@ -62,9 +62,9 @@ INCDIR= /usr/include
 # ${LIBDIR}		where calc link library (*.a) files are installed
 # ${CALC_SHAREDIR}	where to install calc help, .cal, startup, config files
 #
-# NOTE: The install rule prepends installation paths with $T, which
-#	by default is empty.  If $T is non-empty, then installation
-#	locations will be relative to the $T directory.
+# NOTE: The install rule prepends installation paths with ${T}, which
+#	by default is empty.  If ${T} is non-empty, then installation
+#	locations will be relative to the ${T} directory.
 #
 # For DJGPP, select:
 #
@@ -99,9 +99,9 @@ CALC_SHAREDIR= /usr/share/calc
 # ${CUSTOMINCPDIR}	where custom .h files are installed
 # ${SCRIPTDIR}		where calc shell scripts are installed
 #
-# NOTE: The install rule prepends installation paths with $T, which
-#	by default is empty.  If $T is non-empty, then installation
-#	locations will be relative to the $T directory.
+# NOTE: The install rule prepends installation paths with ${T}, which
+#	by default is empty.  If ${T} is non-empty, then installation
+#	locations will be relative to the ${T} directory.
 #
 # If in doubt, set:
 #
@@ -121,8 +121,8 @@ SCRIPTDIR= ${BINDIR}/cscript
 
 # T - top level directory under which calc will be installed
 #
-# The calc install is performed under $T, the calc build is
-# performed under /.	The purpose for $T is to allow someone
+# The calc install is performed under ${T}, the calc build is
+# performed under /.	The purpose for ${T} is to allow someone
 # to install calc somewhere other than into the system area.
 #
 # For example, if:
@@ -142,10 +142,10 @@ SCRIPTDIR= ${BINDIR}/cscript
 #     calc help, .cal ...:	/var/tmp/testing/usr/share/calc
 #     ... etc ...		/var/tmp/testing/...
 #
-# If $T is empty, calc is installed under /, which is the same
-# top of tree for which it was built.  If $T is non-empty, then
-# calc is installed under $T, as if one had to chroot under
-# $T for calc to operate.
+# If ${T} is empty, calc is installed under /, which is the same
+# top of tree for which it was built.  If ${T} is non-empty, then
+# calc is installed under ${T}, as if one had to chroot under
+# ${T} for calc to operate.
 #
 # If in doubt, use T=
 #
@@ -166,6 +166,14 @@ SED= sed
 SORT= sort
 FMT= fmt
 CMP= cmp
+MKDIR= mkdir
+RMDIR= rmdir
+RM= rm
+TOUCH= touch
+MV= mv
+CP= cp
+CO= co
+TRUE= true
 
 # The ${SCRIPT} list is the list of calc shell script files (without the .calc
 # extension) which will be installed.
@@ -199,7 +207,7 @@ CALCLIBLIST=
 
 # complete list of targets
 #
-# NOTE: This list MUST be co-ordinated with the ${CSCRIPT_TARGETS} variable
+# NOTE: This list MUST be coordinated with the ${CSCRIPT_TARGETS} variable
 #	in the upper level ../Makefile
 #
 CSCRIPT_TARGETS= ${SCRIPT}
@@ -215,8 +223,8 @@ all: ${TARGETS} .all
 #	a non-empty else clause for every if condition.  *sigh*
 #
 .all:
-	rm -f .all
-	touch .all
+	${RM} -f .all
+	${TOUCH} .all
 
 ##
 #
@@ -257,7 +265,7 @@ detaillist:
 		   -e 's/$$/ \\/' -e '$$s/ \\$$//'
 	${Q} echo
 	${Q} -(echo "xxxxxxxxxxx"; \
-	   for i in ${SCRIPT} /dev/null; do \
+	    for i in ${SCRIPT} /dev/null; do \
 	    if [ X"$$i" != X"/dev/null" ]; then \
 		if [ ! -f RCS/$$i.calc,v ]; then \
 		    echo "WARNING: $$i.calc not under RCS control" 1>&2; \
@@ -283,12 +291,12 @@ detaillist:
 
 depend:
 	${Q} if [ -f Makefile.bak ]; then \
-		echo "Makefile.bak exists, remove or move it out of the way"; \
-		exit 1; \
+	    echo "Makefile.bak exists, remove or move it out of the way"; \
+	    exit 1; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} rm -f makedep.out
+	-${Q} ${RM} -f makedep.out
 	${Q} echo forming cscript dependency list
 	${Q} echo "# DO NOT DELETE THIS LINE -- make depend depends on it." > \
 		makedep.out
@@ -296,32 +304,32 @@ depend:
 	${Q} for i in ${SCRIPT} /dev/null; do \
 	    if [ X"$$i" != X"/dev/null" ]; then \
 		echo "$$i: $$i.calc"; \
-		echo '	@rm -f $$@'; \
+		echo '	@$${RM} -f $$@'; \
 		echo '	@$${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!$${BINDIR}/calc:" $$?>$$@'; \
 		echo '	@$${CHMOD} +x $$@'; \
 	    fi; \
 	done >> makedep.out
 	${Q} echo sample dependency list formed
 	${Q} echo forming new cscript/Makefile
-	-${Q} rm -f Makefile.bak
-	${Q} mv Makefile Makefile.bak
+	-${Q} ${RM} -f Makefile.bak
+	${Q} ${MV} Makefile Makefile.bak
 	${Q} ${SED} -n '1,/^# DO NOT DELETE THIS LINE/p' Makefile.bak > Makefile
 	${Q} echo "" >> Makefile
 	${Q} ${SED} -n '3,$$p' makedep.out >> Makefile
-	-${Q} rm -f makedep.out
+	-${Q} ${RM} -f makedep.out
 	-${Q} if ${CMP} -s Makefile.bak Makefile; then \
-		echo 'sample Makefile was already up to date'; \
-		mv -f Makefile.bak Makefile; \
+	    echo 'sample Makefile was already up to date'; \
+	    ${MV} -f Makefile.bak Makefile; \
 	else \
-		rm -f Makefile.tmp; \
-		mv Makefile Makefile.tmp; \
-		if [ -d RCS ]; then \
-		    co -l Makefile; \
-		fi; \
-		mv Makefile.tmp Makefile; \
-		if [ -d RCS ]; then \
-		    echo new sample Makefile formed, you need to check it in; \
-		fi; \
+	    ${RM} -f Makefile.tmp; \
+	    ${MV} Makefile Makefile.tmp; \
+	    if [ -d RCS ]; then \
+		${CO} -l Makefile; \
+	    fi; \
+	    ${MV} Makefile.tmp Makefile; \
+	    if [ -d RCS ]; then \
+		echo new sample Makefile formed, you need to check it in; \
+	    fi; \
 	fi
 
 ##
@@ -344,52 +352,52 @@ echo_inst_files:
 ##
 
 clean:
-	-rm -f makedep.out
+	-${RM} -f makedep.out
 
 clobber:
-	-rm -f ${TARGETS}
+	-${RM} -f ${TARGETS}
 
 # install everything
 #
 # NOTE: Keep the uninstall rule in reverse order to the install rule
 #
 install: all
-	-${Q} if [ ! -d $T${BINDIR} ]; then \
-	    echo mkdir $T${BINDIR}; \
-	    mkdir $T${BINDIR}; \
-	    if [ ! -d "$T${BINDIR}" ]; then \
-		echo mkdir -p "$T${BINDIR}"; \
-		mkdir -p "$T${BINDIR}"; \
+	-${Q} if [ ! -d ${T}${BINDIR} ]; then \
+	    echo ${MKDIR} ${T}${BINDIR}; \
+	    ${MKDIR} ${T}${BINDIR}; \
+	    if [ ! -d "${T}${BINDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${BINDIR}"; \
+		${MKDIR} -p "${T}${BINDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${BINDIR}; \
-	    ${CHMOD} 0755 $T${BINDIR}; \
+	    echo ${CHMOD} 0755 ${T}${BINDIR}; \
+	    ${CHMOD} 0755 ${T}${BINDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} if [ ! -d $T${SCRIPTDIR} ]; then \
-	    echo mkdir $T${SCRIPTDIR}; \
-	    mkdir $T${SCRIPTDIR}; \
-	    if [ ! -d "$T${SCRIPTDIR}" ]; then \
-		echo mkdir -p "$T${SCRIPTDIR}"; \
-		mkdir -p "$T${SCRIPTDIR}"; \
+	-${Q} if [ ! -d ${T}${SCRIPTDIR} ]; then \
+	    echo ${MKDIR} ${T}${SCRIPTDIR}; \
+	    ${MKDIR} ${T}${SCRIPTDIR}; \
+	    if [ ! -d "${T}${SCRIPTDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${SCRIPTDIR}"; \
+		${MKDIR} -p "${T}${SCRIPTDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${SCRIPTDIR}; \
-	    ${CHMOD} 0755 $T${SCRIPTDIR}; \
+	    echo ${CHMOD} 0755 ${T}${SCRIPTDIR}; \
+	    ${CHMOD} 0755 ${T}${SCRIPTDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 	${Q} for i in ${SCRIPT} /dev/null; do \
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if ${CMP} -s $$i $T${SCRIPTDIR}/$$i; then \
-		true; \
+	    if ${CMP} -s $$i ${T}${SCRIPTDIR}/$$i; then \
+		${TRUE}; \
 	    else \
-		rm -f $T${SCRIPTDIR}/$$i.new; \
-		cp -f $$i $T${SCRIPTDIR}/$$i.new; \
-		${CHMOD} 0555 $T${SCRIPTDIR}/$$i.new; \
-		mv -f $T${SCRIPTDIR}/$$i.new $T${SCRIPTDIR}/$$i; \
-		echo "installed $T${SCRIPTDIR}/$$i"; \
+		${RM} -f ${T}${SCRIPTDIR}/$$i.new; \
+		${CP} -f $$i ${T}${SCRIPTDIR}/$$i.new; \
+		${CHMOD} 0555 ${T}${SCRIPTDIR}/$$i.new; \
+		${MV} -f ${T}${SCRIPTDIR}/$$i.new ${T}${SCRIPTDIR}/$$i; \
+		echo "installed ${T}${SCRIPTDIR}/$$i"; \
 	    fi; \
 	done
 
@@ -402,53 +410,53 @@ uninstall:
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if [ -f "$T${SCRIPTDIR}/$$i" ]; then \
-	    	rm -f "$T${SCRIPTDIR}/$$i"; \
-		if [ -f "$T${SCRIPTDIR}/$$i" ]; then \
-		   echo "cannot uninstall $T${SCRIPTDIR}/$$i"; \
+	    if [ -f "${T}${SCRIPTDIR}/$$i" ]; then \
+	    	${RM} -f "${T}${SCRIPTDIR}/$$i"; \
+		if [ -f "${T}${SCRIPTDIR}/$$i" ]; then \
+		   echo "cannot uninstall ${T}${SCRIPTDIR}/$$i"; \
 		else \
-		   echo "uninstalled $T${SCRIPTDIR}/$$i"; \
+		   echo "uninstalled ${T}${SCRIPTDIR}/$$i"; \
 		fi; \
 	    fi; \
 	done
 	-${Q} for i in ${SCRIPTDIR} ${BINDIR}; do \
-	    if [ -d "$T$$i" ]; then \
-		rmdir "$T$$i" 2>/dev/null; \
-		echo "cleaned up $T$$i"; \
+	    if [ -d "${T}$$i" ]; then \
+		${RMDIR} "${T}$$i" 2>/dev/null; \
+		echo "cleaned up ${T}$$i"; \
 	    fi; \
 	done
 
 # DO NOT DELETE THIS LINE -- make depend depends on it.
 
 4dsphere: 4dsphere.calc
-	@rm -f $@
+	@${RM} -f $@
 	@${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!${BINDIR}/calc:" $?>$@
 	@${CHMOD} +x $@
 fproduct: fproduct.calc
-	@rm -f $@
+	@${RM} -f $@
 	@${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!${BINDIR}/calc:" $?>$@
 	@${CHMOD} +x $@
 mersenne: mersenne.calc
-	@rm -f $@
+	@${RM} -f $@
 	@${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!${BINDIR}/calc:" $?>$@
 	@${CHMOD} +x $@
 piforever: piforever.calc
-	@rm -f $@
+	@${RM} -f $@
 	@${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!${BINDIR}/calc:" $?>$@
 	@${CHMOD} +x $@
 plus: plus.calc
-	@rm -f $@
+	@${RM} -f $@
 	@${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!${BINDIR}/calc:" $?>$@
 	@${CHMOD} +x $@
 powerterm: powerterm.calc
-	@rm -f $@
+	@${RM} -f $@
 	@${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!${BINDIR}/calc:" $?>$@
 	@${CHMOD} +x $@
 simple: simple.calc
-	@rm -f $@
+	@${RM} -f $@
 	@${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!${BINDIR}/calc:" $?>$@
 	@${CHMOD} +x $@
 square: square.calc
-	@rm -f $@
+	@${RM} -f $@
 	@${SED} -e "1s:^#!/usr/local/src/cmd/calc/calc:#!${BINDIR}/calc:" $?>$@
 	@${CHMOD} +x $@
diff --git a/custom/Makefile b/custom/Makefile
--- a/custom/Makefile
+++ b/custom/Makefile
@@ -2,7 +2,7 @@
 #
 # custom - makefile for calc custom routines
 #
-# Copyright (C) 1999,2004  Landon Curt Noll
+# Copyright (C) 1999-2006  Landon Curt Noll
 #
 # Calc is open software; you can redistribute it and/or modify it under
 # the terms of the version 2.1 of the GNU Lesser General Public License
@@ -18,8 +18,8 @@
 # received a copy with calc; if not, write to Free Software Foundation, Inc.
 # 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
 #
-# @(#) $Revision: 29.26 $
-# @(#) $Id: Makefile,v 29.26 2006/09/18 00:13:59 chongo Exp $
+# @(#) $Revision: 29.28 $
+# @(#) $Id: Makefile,v 29.28 2006/09/18 07:04:42 chongo Exp $
 # @(#) $Source: /usr/local/src/cmd/calc/custom/RCS/Makefile,v $
 #
 # Under source code control:	1997/03/09 02:28:54
@@ -114,9 +114,9 @@ INCDIR= /usr/include
 # ${LIBDIR}		where calc link library (*.a) files are installed
 # ${CALC_SHAREDIR}	where to install calc help, .cal, startup, config files
 #
-# NOTE: The install rule prepends installation paths with $T, which
-#	by default is empty.  If $T is non-empty, then installation
-#	locations will be relative to the $T directory.
+# NOTE: The install rule prepends installation paths with ${T}, which
+#	by default is empty.  If ${T} is non-empty, then installation
+#	locations will be relative to the ${T} directory.
 #
 # For DJGPP, select:
 #
@@ -151,9 +151,9 @@ CALC_SHAREDIR= /usr/share/calc
 # ${CUSTOMINCPDIR}	where custom .h files are installed
 # ${SCRIPTDIR}		where calc shell scripts are installed
 #
-# NOTE: The install rule prepends installation paths with $T, which
-#	by default is empty.  If $T is non-empty, then installation
-#	locations will be relative to the $T directory.
+# NOTE: The install rule prepends installation paths with ${T}, which
+#	by default is empty.  If ${T} is non-empty, then installation
+#	locations will be relative to the ${T} directory.
 #
 # If in doubt, set:
 #
@@ -173,8 +173,8 @@ SCRIPTDIR= ${BINDIR}/cscript
 
 # T - top level directory under which calc will be installed
 #
-# The calc install is performed under $T, the calc build is
-# performed under /.	The purpose for $T is to allow someone
+# The calc install is performed under ${T}, the calc build is
+# performed under /.	The purpose for ${T} is to allow someone
 # to install calc somewhere other than into the system area.
 #
 # For example, if:
@@ -194,10 +194,10 @@ SCRIPTDIR= ${BINDIR}/cscript
 #     calc help, .cal ...:	/var/tmp/testing/usr/share/calc
 #     ... etc ...		/var/tmp/testing/...
 #
-# If $T is empty, calc is installed under /, which is the same
-# top of tree for which it was built.  If $T is non-empty, then
-# calc is installed under $T, as if one had to chroot under
-# $T for calc to operate.
+# If ${T} is empty, calc is installed under /, which is the same
+# top of tree for which it was built.  If ${T} is non-empty, then
+# calc is installed under ${T}, as if one had to chroot under
+# ${T} for calc to operate.
 #
 # If in doubt, use T=
 #
@@ -402,6 +402,15 @@ MAKEDEPEND= makedepend
 CHMOD= chmod
 SORT= sort
 CMP= cmp
+AR= ar
+RM= rm
+TOUCH= touch
+MKDIR= mkdir
+RMDIR= rmdir
+MV= mv
+CP= cp
+CO= co
+TRUE= true
 
 ##
 #
@@ -413,8 +422,8 @@ all: ${TARGETS} ${INSTALL_H_SRC} ${CUSTOM_CALC_FILES} \
 	${CUSTOM_HELP} ${MAKE_FILE} .all
 
 libcustcalc.a: ${CUSTCALC_OBJ} ${MAKE_FILE} ../${MAKE_FILE}
-	-rm -f libcustcalc.a
-	ar qc libcustcalc.a ${CUSTCALC_OBJ}
+	-${RM} -f libcustcalc.a
+	${AR} qc libcustcalc.a ${CUSTCALC_OBJ}
 	${RANLIB} libcustcalc.a
 
 ##
@@ -435,8 +444,8 @@ c_sysinfo.o: c_sysinfo.c ${MAKE_FILE}
 # to determine of we have done all
 #
 .all:
-	rm -f .all
-	touch .all
+	${RM} -f .all
+	${TOUCH} .all
 
 ##
 #
@@ -482,15 +491,15 @@ calcliblist: ${CALCLIBLIST}
 
 depend:
 	${Q} if [ -f Makefile.bak ]; then \
-		echo "Makefile.bak exists, remove or move it out of the way"; \
-		exit 1; \
+	    echo "Makefile.bak exists, remove or move it out of the way"; \
+	    exit 1; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 	${Q} echo forming custom/skel
-	-${Q} rm -rf skel
-	${Q} mkdir skel
-	${Q} mkdir skel/custom
+	-${Q} ${RM} -rf skel
+	${Q} ${MKDIR} skel
+	${Q} ${MKDIR} skel/custom
 	-${Q} for i in ${C_SRC} /dev/null; do \
 	    if [ X"$$i" != X"/dev/null" ]; then \
 		${SED} -n '/^#[	 ]*include[	 ]*"/p' \
@@ -498,32 +507,32 @@ depend:
 	    fi; \
 	done
 	-${Q} for i in ${H_SRC} /dev/null; do \
-		if [ "$$i" = "/dev/null" ]; then \
-		    continue; \
-		fi; \
-		tag="`echo $$i | ${SED} 's/[\.+,:]/_/g'`"; \
-		echo "#if !defined($$tag)" > "skel/custom/$$i"; \
-		echo "#define $$tag" >> "skel/custom/$$i"; \
-		${SED} -n '/^#[	 ]*include[	 ]*"/p' "$$i" \
-		    >> "skel/custom/$$i"; \
-		echo '#endif /* '"$$tag"' */' >> "skel/custom/$$i"; \
+	    if [ "$$i" = "/dev/null" ]; then \
+		continue; \
+	    fi; \
+	    tag="`echo $$i | ${SED} 's/[\.+,:]/_/g'`"; \
+	    echo "#if !defined($$tag)" > "skel/custom/$$i"; \
+	    echo "#define $$tag" >> "skel/custom/$$i"; \
+	    ${SED} -n '/^#[	 ]*include[	 ]*"/p' "$$i" \
+		>> "skel/custom/$$i"; \
+	    echo '#endif /* '"$$tag"' */' >> "skel/custom/$$i"; \
 	done
 	${Q} (cd ..; ${MAKE} hsrc)
 	${Q} for i in `cd ..; ${MAKE} h_list 2>&1 | \
-			     ${SED} -e '/Entering directory/d' \
-				    -e '/Nothing to be done/d' \
-				    -e '/Leaving directory/d'` /dev/null; do \
-		if [ "$$i" = "/dev/null" ]; then \
-		    continue; \
-		fi; \
-		tag="`echo $$i | ${SED} 's/[\.+,:]/_/g'`"; \
-		echo "#if !defined($$tag)" > "skel/$$i"; \
-		echo "#define $$tag" >> "skel/$$i"; \
-		${SED} -n '/^#[	 ]*include[	 ]*"/p' "../$$i" \
-		    >> "skel/$$i"; \
-		echo '#endif /* '"$$tag"' */' >> "skel/$$i"; \
+	    ${SED} -e '/Entering directory/d' \
+		   -e '/Nothing to be done/d' \
+		   -e '/Leaving directory/d'` /dev/null; do \
+	    if [ "$$i" = "/dev/null" ]; then \
+		continue; \
+	    fi; \
+	    tag="`echo $$i | ${SED} 's/[\.+,:]/_/g'`"; \
+	    echo "#if !defined($$tag)" > "skel/$$i"; \
+	    echo "#define $$tag" >> "skel/$$i"; \
+	    ${SED} -n '/^#[	 ]*include[	 ]*"/p' "../$$i" \
+		>> "skel/$$i"; \
+	    echo '#endif /* '"$$tag"' */' >> "skel/$$i"; \
 	done
-	-${Q} rm -f skel/custom/makedep.out
+	-${Q} ${RM} -f skel/custom/makedep.out
 	${Q} echo custom/skel formed
 	${Q} echo forming custom dependency list
 	${Q} echo "# DO NOT DELETE THIS LINE -- make depend depends on it." > \
@@ -536,26 +545,26 @@ depend:
 	done >> skel/custom/makedep.out
 	${Q} echo custom dependency list formed
 	${Q} echo forming new custom/Makefile
-	-${Q} rm -f Makefile.bak
-	${Q} mv Makefile Makefile.bak
+	-${Q} ${RM} -f Makefile.bak
+	${Q} ${MV} Makefile Makefile.bak
 	${Q} ${SED} -n '1,/^# DO NOT DELETE THIS LINE/p' Makefile.bak > Makefile
 	${Q} echo "" >> Makefile
 	${Q} ${SED} -n '3,$$p' skel/custom/makedep.out | \
 		LANG=C ${SORT} -u >> Makefile
-	-${Q} rm -rf skel
+	-${Q} ${RM} -rf skel
 	-${Q} if ${CMP} -s Makefile.bak Makefile; then \
-		echo 'custom Makefile was already up to date'; \
-		mv -f Makefile.bak Makefile; \
+	    echo 'custom Makefile was already up to date'; \
+	    ${MV} -f Makefile.bak Makefile; \
 	else \
-		rm -f Makefile.tmp; \
-		mv Makefile Makefile.tmp; \
-		if [ -d RCS ]; then \
-		    co -l Makefile; \
-		fi ;\
-		mv Makefile.tmp Makefile; \
-		if [ -d RCS ]; then \
-		echo 'new custom Makefile formed -- you need to check it in'; \
-		fi; \
+	    ${RM} -f Makefile.tmp; \
+	    ${MV} Makefile Makefile.tmp; \
+	    if [ -d RCS ]; then \
+		${CO} -l Makefile; \
+	    fi ;\
+	    ${MV} Makefile.tmp Makefile; \
+	    if [ -d RCS ]; then \
+	    echo 'new custom Makefile formed -- you need to check it in'; \
+	    fi; \
 	fi
 
 ##
@@ -593,154 +602,154 @@ echo_inst_files:
 ##
 
 clean:
-	-rm -f ${CUSTCALC_OBJ}
+	-${RM} -f ${CUSTCALC_OBJ}
 
 clobber:
-	-rm -f ${TARGETS}
-	rm -f .all Makefile.tmp Makefile.bak
+	-${RM} -f ${TARGETS}
+	${RM} -f .all Makefile.tmp Makefile.bak
 
 # install everything
 #
 # NOTE: Keep the uninstall rule in reverse order to the install rule
 #
 install: all
-	-${Q} if [ ! -d $T${INCDIR} ]; then \
-	    echo mkdir $T${INCDIR}; \
-	    mkdir $T${INCDIR}; \
-	    if [ ! -d "$T${INCDIR}" ]; then \
-		echo mkdir -p "$T${INCDIR}"; \
-		mkdir -p "$T${INCDIR}"; \
+	-${Q} if [ ! -d ${T}${INCDIR} ]; then \
+	    echo ${MKDIR} ${T}${INCDIR}; \
+	    ${MKDIR} ${T}${INCDIR}; \
+	    if [ ! -d "${T}${INCDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${INCDIR}"; \
+		${MKDIR} -p "${T}${INCDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${INCDIR}; \
-	    ${CHMOD} 0755 $T${INCDIR}; \
+	    echo ${CHMOD} 0755 ${T}${INCDIR}; \
+	    ${CHMOD} 0755 ${T}${INCDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} if [ ! -d $T${CALC_SHAREDIR} ]; then \
-	    echo mkdir $T${CALC_SHAREDIR}; \
-	    mkdir $T${CALC_SHAREDIR}; \
-	    if [ ! -d "$T${CALC_SHAREDIR}" ]; then \
-		echo mkdir -p "$T${CALC_SHAREDIR}"; \
-		mkdir -p "$T${CALC_SHAREDIR}"; \
+	-${Q} if [ ! -d ${T}${CALC_SHAREDIR} ]; then \
+	    echo ${MKDIR} ${T}${CALC_SHAREDIR}; \
+	    ${MKDIR} ${T}${CALC_SHAREDIR}; \
+	    if [ ! -d "${T}${CALC_SHAREDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${CALC_SHAREDIR}"; \
+		${MKDIR} -p "${T}${CALC_SHAREDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${CALC_SHAREDIR}; \
-	    ${CHMOD} 0755 $T${CALC_SHAREDIR}; \
+	    echo ${CHMOD} 0755 ${T}${CALC_SHAREDIR}; \
+	    ${CHMOD} 0755 ${T}${CALC_SHAREDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} if [ ! -d $T${CALC_INCDIR} ]; then \
-	    echo mkdir $T${CALC_INCDIR}; \
-	    mkdir $T${CALC_INCDIR}; \
-	    if [ ! -d "$T${CALC_INCDIR}" ]; then \
-		echo mkdir -p "$T${CALC_INCDIR}"; \
-		mkdir -p "$T${CALC_INCDIR}"; \
+	-${Q} if [ ! -d ${T}${CALC_INCDIR} ]; then \
+	    echo ${MKDIR} ${T}${CALC_INCDIR}; \
+	    ${MKDIR} ${T}${CALC_INCDIR}; \
+	    if [ ! -d "${T}${CALC_INCDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${CALC_INCDIR}"; \
+		${MKDIR} -p "${T}${CALC_INCDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${CALC_INCDIR}; \
-	    ${CHMOD} 0755 $T${CALC_INCDIR}; \
+	    echo ${CHMOD} 0755 ${T}${CALC_INCDIR}; \
+	    ${CHMOD} 0755 ${T}${CALC_INCDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} if [ ! -d $T${HELPDIR} ]; then \
-	    echo mkdir $T${HELPDIR}; \
-	    mkdir $T${HELPDIR}; \
-	    if [ ! -d "$T${HELPDIR}" ]; then \
-		echo mkdir -p "$T${HELPDIR}"; \
-		mkdir -p "$T${HELPDIR}"; \
+	-${Q} if [ ! -d ${T}${HELPDIR} ]; then \
+	    echo ${MKDIR} ${T}${HELPDIR}; \
+	    ${MKDIR} ${T}${HELPDIR}; \
+	    if [ ! -d "${T}${HELPDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${HELPDIR}"; \
+		${MKDIR} -p "${T}${HELPDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${HELPDIR}; \
-	    ${CHMOD} 0755 $T${HELPDIR}; \
+	    echo ${CHMOD} 0755 ${T}${HELPDIR}; \
+	    ${CHMOD} 0755 ${T}${HELPDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} if [ ! -d $T${CUSTOMCALDIR} ]; then \
-	    echo mkdir $T${CUSTOMCALDIR}; \
-	    mkdir $T${CUSTOMCALDIR}; \
-	    if [ ! -d "$T${CUSTOMCALDIR}" ]; then \
-		echo mkdir -p "$T${CUSTOMCALDIR}"; \
-		mkdir -p "$T${CUSTOMCALDIR}"; \
+	-${Q} if [ ! -d ${T}${CUSTOMCALDIR} ]; then \
+	    echo ${MKDIR} ${T}${CUSTOMCALDIR}; \
+	    ${MKDIR} ${T}${CUSTOMCALDIR}; \
+	    if [ ! -d "${T}${CUSTOMCALDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${CUSTOMCALDIR}"; \
+		${MKDIR} -p "${T}${CUSTOMCALDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${CUSTOMCALDIR}; \
-	    ${CHMOD} 0755 $T${CUSTOMCALDIR}; \
+	    echo ${CHMOD} 0755 ${T}${CUSTOMCALDIR}; \
+	    ${CHMOD} 0755 ${T}${CUSTOMCALDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} if [ ! -d $T${CUSTOMHELPDIR} ]; then \
-	    echo mkdir $T${CUSTOMHELPDIR}; \
-	    mkdir $T${CUSTOMHELPDIR}; \
-	    if [ ! -d "$T${CUSTOMHELPDIR}" ]; then \
-		echo mkdir -p "$T${CUSTOMHELPDIR}"; \
-		mkdir -p "$T${CUSTOMHELPDIR}"; \
+	-${Q} if [ ! -d ${T}${CUSTOMHELPDIR} ]; then \
+	    echo ${MKDIR} ${T}${CUSTOMHELPDIR}; \
+	    ${MKDIR} ${T}${CUSTOMHELPDIR}; \
+	    if [ ! -d "${T}${CUSTOMHELPDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${CUSTOMHELPDIR}"; \
+		${MKDIR} -p "${T}${CUSTOMHELPDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${CUSTOMHELPDIR}; \
-	    ${CHMOD} 0755 $T${CUSTOMHELPDIR}; \
+	    echo ${CHMOD} 0755 ${T}${CUSTOMHELPDIR}; \
+	    ${CHMOD} 0755 ${T}${CUSTOMHELPDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} if [ ! -d $T${CUSTOMINCDIR} ]; then \
-	    echo mkdir $T${CUSTOMINCDIR}; \
-	    mkdir $T${CUSTOMINCDIR}; \
-	    if [ ! -d "$T${CUSTOMINCDIR}" ]; then \
-		echo mkdir -p "$T${CUSTOMINCDIR}"; \
-		mkdir -p "$T${CUSTOMINCDIR}"; \
+	-${Q} if [ ! -d ${T}${CUSTOMINCDIR} ]; then \
+	    echo ${MKDIR} ${T}${CUSTOMINCDIR}; \
+	    ${MKDIR} ${T}${CUSTOMINCDIR}; \
+	    if [ ! -d "${T}${CUSTOMINCDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${CUSTOMINCDIR}"; \
+		${MKDIR} -p "${T}${CUSTOMINCDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${CUSTOMINCDIR}; \
-	    ${CHMOD} 0755 $T${CUSTOMINCDIR}; \
+	    echo ${CHMOD} 0755 ${T}${CUSTOMINCDIR}; \
+	    ${CHMOD} 0755 ${T}${CUSTOMINCDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 	-${Q} for i in ${INSTALL_H_SRC} /dev/null; do \
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if ${CMP} -s "$$i" $T${CUSTOMINCDIR}/$$i; then \
-		true; \
+	    if ${CMP} -s "$$i" ${T}${CUSTOMINCDIR}/$$i; then \
+		${TRUE}; \
 	    else \
-		rm -f $T${CUSTOMINCDIR}/$$i.new; \
-		cp -f $$i $T${CUSTOMINCDIR}/$$i.new; \
-		${CHMOD} 0444 $T${CUSTOMINCDIR}/$$i.new; \
-		mv -f $T${CUSTOMINCDIR}/$$i.new $T${CUSTOMINCDIR}/$$i; \
-		echo "installed $T${CUSTOMINCDIR}/$$i"; \
+		${RM} -f ${T}${CUSTOMINCDIR}/$$i.new; \
+		${CP} -f $$i ${T}${CUSTOMINCDIR}/$$i.new; \
+		${CHMOD} 0444 ${T}${CUSTOMINCDIR}/$$i.new; \
+		${MV} -f ${T}${CUSTOMINCDIR}/$$i.new ${T}${CUSTOMINCDIR}/$$i; \
+		echo "installed ${T}${CUSTOMINCDIR}/$$i"; \
 	    fi; \
 	done
 	-${Q} for i in ${CUSTOM_CALC_FILES} /dev/null; do \
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if ${CMP} -s $$i $T${CUSTOMCALDIR}/$$i; then \
-		true; \
+	    if ${CMP} -s $$i ${T}${CUSTOMCALDIR}/$$i; then \
+		${TRUE}; \
 	    else \
-		rm -f $T${CUSTOMCALDIR}/$$i.new; \
-		cp -f $$i $T${CUSTOMCALDIR}/$$i.new; \
-		${CHMOD} 0444 $T${CUSTOMCALDIR}/$$i.new; \
-		mv -f $T${CUSTOMCALDIR}/$$i.new $T${CUSTOMCALDIR}/$$i; \
-		echo "installed $T${CUSTOMCALDIR}/$$i"; \
+		${RM} -f ${T}${CUSTOMCALDIR}/$$i.new; \
+		${CP} -f $$i ${T}${CUSTOMCALDIR}/$$i.new; \
+		${CHMOD} 0444 ${T}${CUSTOMCALDIR}/$$i.new; \
+		${MV} -f ${T}${CUSTOMCALDIR}/$$i.new ${T}${CUSTOMCALDIR}/$$i; \
+		echo "installed ${T}${CUSTOMCALDIR}/$$i"; \
 	    fi; \
 	done
 	-${Q} for i in ${CUSTOM_HELP} /dev/null; do \
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if ${CMP} -s $$i $T${CUSTOMHELPDIR}/$$i; then \
-		true; \
+	    if ${CMP} -s $$i ${T}${CUSTOMHELPDIR}/$$i; then \
+		${TRUE}; \
 	    else \
-		rm -f $T${CUSTOMHELPDIR}/$$i.new; \
-		cp -f $$i $T${CUSTOMHELPDIR}/$$i.new; \
-		${CHMOD} 0444 $T${CUSTOMHELPDIR}/$$i.new; \
-		mv -f $T${CUSTOMHELPDIR}/$$i.new $T${CUSTOMHELPDIR}/$$i; \
-		echo "installed $T${CUSTOMHELPDIR}/$$i"; \
+		${RM} -f ${T}${CUSTOMHELPDIR}/$$i.new; \
+		${CP} -f $$i ${T}${CUSTOMHELPDIR}/$$i.new; \
+		${CHMOD} 0444 ${T}${CUSTOMHELPDIR}/$$i.new; \
+		${MV} -f ${T}${CUSTOMHELPDIR}/$$i.new ${T}${CUSTOMHELPDIR}/$$i; \
+		echo "installed ${T}${CUSTOMHELPDIR}/$$i"; \
 	    fi; \
 	done
 	-${Q} if [ ! -z ${ALLOW_CUSTOM} ]; then \
-	    if ${CMP} -s libcustcalc.a $T${CUSTOMCALDIR}/libcustcalc.a; then \
-		true; \
+	    if ${CMP} -s libcustcalc.a ${T}${CUSTOMCALDIR}/libcustcalc.a; then \
+		${TRUE}; \
 	    else \
-		rm -f $T${CUSTOMCALDIR}/libcustcalc.a.new; \
-		cp -f libcustcalc.a $T${CUSTOMCALDIR}/libcustcalc.a.new; \
-		${CHMOD} 0644 $T${CUSTOMCALDIR}/libcustcalc.a.new; \
-		mv -f $T${CUSTOMCALDIR}/libcustcalc.a.new \
-		      $T${CUSTOMCALDIR}/libcustcalc.a; \
-		${RANLIB} $T${CUSTOMCALDIR}/libcustcalc.a; \
-		echo "installed $T${CUSTOMCALDIR}/libcustcalc.a"; \
+		${RM} -f ${T}${CUSTOMCALDIR}/libcustcalc.a.new; \
+		${CP} -f libcustcalc.a ${T}${CUSTOMCALDIR}/libcustcalc.a.new; \
+		${CHMOD} 0644 ${T}${CUSTOMCALDIR}/libcustcalc.a.new; \
+		${MV} -f ${T}${CUSTOMCALDIR}/libcustcalc.a.new \
+		      ${T}${CUSTOMCALDIR}/libcustcalc.a; \
+		${RANLIB} ${T}${CUSTOMCALDIR}/libcustcalc.a; \
+		echo "installed ${T}${CUSTOMCALDIR}/libcustcalc.a"; \
 	    fi; \
 	fi
 
@@ -749,24 +758,24 @@ install: all
 # NOTE: Keep the uninstall rule in reverse order to the install rule
 #
 uninstall:
-	-${Q} if [ -f "$T${CUSTOMCALDIR}/libcustcalc.a" ]; then \
-	    rm -f "$T${CUSTOMCALDIR}/libcustcalc.a"; \
-	    if [ -f "$T${CUSTOMCALDIR}/libcustcalc.a" ]; then \
-		echo "cannot uninstall $T${CUSTOMCALDIR}/libcustcalc.a"; \
+	-${Q} if [ -f "${T}${CUSTOMCALDIR}/libcustcalc.a" ]; then \
+	    ${RM} -f "${T}${CUSTOMCALDIR}/libcustcalc.a"; \
+	    if [ -f "${T}${CUSTOMCALDIR}/libcustcalc.a" ]; then \
+		echo "cannot uninstall ${T}${CUSTOMCALDIR}/libcustcalc.a"; \
 	    else \
-		echo "uninstalled $T${CUSTOMCALDIR}/libcustcalc.a"; \
+		echo "uninstalled ${T}${CUSTOMCALDIR}/libcustcalc.a"; \
 	    fi; \
 	fi
 	-${Q} for i in ${CUSTOM_HELP} /dev/null; do \
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if [ -f "$T${CUSTOMHELPDIR}/$$i" ]; then \
-	    	rm -f "$T${CUSTOMHELPDIR}/$$i"; \
-		if [ -f "$T${CUSTOMHELPDIR}/$$i" ]; then \
-		   echo "cannot uninstall $T${CUSTOMHELPDIR}/$$i"; \
+	    if [ -f "${T}${CUSTOMHELPDIR}/$$i" ]; then \
+	    	${RM} -f "${T}${CUSTOMHELPDIR}/$$i"; \
+		if [ -f "${T}${CUSTOMHELPDIR}/$$i" ]; then \
+		   echo "cannot uninstall ${T}${CUSTOMHELPDIR}/$$i"; \
 		else \
-		   echo "uninstalled $T${CUSTOMHELPDIR}/$$i"; \
+		   echo "uninstalled ${T}${CUSTOMHELPDIR}/$$i"; \
 		fi; \
 	    fi; \
 	done
@@ -774,12 +783,12 @@ uninstall:
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if [ -f "$T${CUSTOMCALDIR}/$$i" ]; then \
-	    	rm -f "$T${CUSTOMCALDIR}/$$i"; \
-		if [ -f "$T${CUSTOMCALDIR}/$$i" ]; then \
-		   echo "cannot uninstall $T${CUSTOMCALDIR}/$$i"; \
+	    if [ -f "${T}${CUSTOMCALDIR}/$$i" ]; then \
+	    	${RM} -f "${T}${CUSTOMCALDIR}/$$i"; \
+		if [ -f "${T}${CUSTOMCALDIR}/$$i" ]; then \
+		   echo "cannot uninstall ${T}${CUSTOMCALDIR}/$$i"; \
 		else \
-		   echo "uninstalled $T${CUSTOMCALDIR}/$$i"; \
+		   echo "uninstalled ${T}${CUSTOMCALDIR}/$$i"; \
 		fi; \
 	    fi; \
 	done
@@ -787,20 +796,20 @@ uninstall:
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if [ -f "$T${CUSTOMINCDIR}/$$i" ]; then \
-	    	rm -f "$T${CUSTOMINCDIR}/$$i"; \
-		if [ -f "$T${CUSTOMINCDIR}/$$i" ]; then \
-		   echo "cannot uninstall $T${CUSTOMINCDIR}/$$i"; \
+	    if [ -f "${T}${CUSTOMINCDIR}/$$i" ]; then \
+	    	${RM} -f "${T}${CUSTOMINCDIR}/$$i"; \
+		if [ -f "${T}${CUSTOMINCDIR}/$$i" ]; then \
+		   echo "cannot uninstall ${T}${CUSTOMINCDIR}/$$i"; \
 		else \
-		   echo "uninstalled $T${CUSTOMINCDIR}/$$i"; \
+		   echo "uninstalled ${T}${CUSTOMINCDIR}/$$i"; \
 		fi; \
 	    fi; \
 	done
 	-${Q} for i in ${CUSTOMINCDIR} ${CUSTOMHELPDIR} ${CUSTOMCALDIR} \
 		    ${HELPDIR} ${CALC_INCDIR} ${CALC_SHAREDIR} ${INCDIR}; do \
-	    if [ -d "$T$$i" ]; then \
-		rmdir "$T$$i" 2>/dev/null; \
-		echo "cleaned up $T$$i"; \
+	    if [ -d "${T}$$i" ]; then \
+		${RMDIR} "${T}$$i" 2>/dev/null; \
+		echo "cleaned up ${T}$$i"; \
 	    fi; \
 	done
 
diff --git a/help/Makefile b/help/Makefile
--- a/help/Makefile
+++ b/help/Makefile
@@ -2,7 +2,7 @@
 #
 # help - makefile for calc help files
 #
-# Copyright (C) 1999-2002  Landon Curt Noll
+# Copyright (C) 1999-2006  Landon Curt Noll
 #
 # Calc is open software; you can redistribute it and/or modify it under
 # the terms of the version 2.1 of the GNU Lesser General Public License
@@ -18,8 +18,8 @@
 # received a copy with calc; if not, write to Free Software Foundation, Inc.
 # 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
 #
-# @(#) $Revision: 29.31 $
-# @(#) $Id: Makefile,v 29.31 2006/09/18 00:13:59 chongo Exp $
+# @(#) $Revision: 29.33 $
+# @(#) $Id: Makefile,v 29.33 2006/09/18 07:04:42 chongo Exp $
 # @(#) $Source: /usr/local/src/cmd/calc/help/RCS/Makefile,v $
 #
 # Under source code control:	1991/07/23 06:47:57
@@ -62,9 +62,9 @@ INCDIR= /usr/include
 # ${LIBDIR}		where calc link library (*.a) files are installed
 # ${CALC_SHAREDIR}	where to install calc help, .cal, startup, config files
 #
-# NOTE: The install rule prepends installation paths with $T, which
-#	by default is empty.  If $T is non-empty, then installation
-#	locations will be relative to the $T directory.
+# NOTE: The install rule prepends installation paths with ${T}, which
+#	by default is empty.  If ${T} is non-empty, then installation
+#	locations will be relative to the ${T} directory.
 #
 # For DJGPP, select:
 #
@@ -99,9 +99,9 @@ CALC_SHAREDIR= /usr/share/calc
 # ${CUSTOMINCPDIR}	where custom .h files are installed
 # ${SCRIPTDIR}		where calc shell scripts are installed
 #
-# NOTE: The install rule prepends installation paths with $T, which
-#	by default is empty.  If $T is non-empty, then installation
-#	locations will be relative to the $T directory.
+# NOTE: The install rule prepends installation paths with ${T}, which
+#	by default is empty.  If ${T} is non-empty, then installation
+#	locations will be relative to the ${T} directory.
 #
 # If in doubt, set:
 #
@@ -121,8 +121,8 @@ SCRIPTDIR= ${BINDIR}/cscript
 
 # T - top level directory under which calc will be installed
 #
-# The calc install is performed under $T, the calc build is
-# performed under /.	The purpose for $T is to allow someone
+# The calc install is performed under ${T}, the calc build is
+# performed under /.	The purpose for ${T} is to allow someone
 # to install calc somewhere other than into the system area.
 #
 # For example, if:
@@ -142,10 +142,10 @@ SCRIPTDIR= ${BINDIR}/cscript
 #     calc help, .cal ...:	/var/tmp/testing/usr/share/calc
 #     ... etc ...		/var/tmp/testing/...
 #
-# If $T is empty, calc is installed under /, which is the same
-# top of tree for which it was built.  If $T is non-empty, then
-# calc is installed under $T, as if one had to chroot under
-# $T for calc to operate.
+# If ${T} is empty, calc is installed under /, which is the same
+# top of tree for which it was built.  If ${T} is non-empty, then
+# calc is installed under ${T}, as if one had to chroot under
+# ${T} for calc to operate.
 #
 # If in doubt, use T=
 #
@@ -169,6 +169,14 @@ SED= sed
 SORT= sort
 FMT= fmt
 CMP= cmp
+CP= cm
+MV= mv
+TRUE= true
+RM= rm
+MKDIR= mkdir
+RMDIR= rmdir
+TOUCH= touch
+CAT= cat
 
 # Some out of date operating systems require / want an executable to
 # end with a certain file extension.  Some compile systems such as
@@ -269,7 +277,7 @@ DETAIL_HELP= abs access acos acosh acot acoth acsc acsch address agd append \
 	appr arg argv arrow asec asech asin asinh assign atan atan2 atanh \
 	avg base base2 bernoulli bit blk blkcpy blkfree blocks bround \
 	btrunc calc_tty calclevel catalan ceil cfappr cfsim char cmdbuf \
-	cmp comb conj cos cosh cot coth count cp csc csch ctime delete den \
+	cmp comb conj cos cosh cot coth count ${CP} csc csch ctime delete den \
 	dereference det digit digits display dp epsilon errcount errmax \
 	errno error estr euler eval exp fact factor fclose fcnt feof ferror \
 	fflush fgetc fgetfield fgetfile fgetline fgets fgetstr fib files \
@@ -287,7 +295,7 @@ DETAIL_HELP= abs access acos acosh acot acoth acsc acsch address agd append \
 	param perm pfact pi pix places pmod polar poly pop popcnt power \
 	prevcand prevprime printf prompt protect ptest push putenv quo \
 	quomod rand randbit random randombit randperm rcin rcmul rcout \
-	rcpow rcsq re remove reverse rewind rm root round rsearch runtime \
+	rcpow rcsq re remove reverse rewind ${RM} root round rsearch runtime \
 	saveval scale scan scanf search sec sech seed segment select sgn \
 	sha sha1 sin sinh size sizeof sleep sort sqrt srand srandom ssq \
 	str strcat strcmp strcpy strerror strlen strncmp strncpy strpos \
@@ -325,175 +333,175 @@ all: ${FULL_HELP_FILES} full ${DETAIL_HELP} ${DETAIL_CLONE} \
 #	an non-emoty else clause for every if condition.  *sigh*
 #
 .all:
-	rm -f .all
-	touch .all
+	${RM} -f .all
+	${TOUCH} .all
 
 bindings: ../cal/bindings
-	rm -f $@
-	cp ../cal/bindings $@
+	${RM} -f $@
+	${CP} ../cal/bindings $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 resource: ../cal/README
-	rm -f $@
-	cp ../cal/README $@
+	${RM} -f $@
+	${CP} ../cal/README $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 changes: ../CHANGES
-	rm -f $@
-	cp ../CHANGES $@
+	${RM} -f $@
+	${CP} ../CHANGES $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 libcalc: ../LIBRARY
-	rm -f $@
+	${RM} -f $@
 	${SED} -e 's:$${LIBDIR}:${LIBDIR}:g' \
 	       -e 's:$${CALC_INCDIR}:${CALC_INCDIR}:g' < ../LIBRARY > $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 bugs: ../BUGS
-	rm -f $@
-	cp ../BUGS $@
+	${RM} -f $@
+	${CP} ../BUGS $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 errorcodes: ../calcerr.h errorcodes.hdr errorcodes.sed
-	rm -f $@
-	cat errorcodes.hdr > $@
+	${RM} -f $@
+	${CAT} errorcodes.hdr > $@
 	${SED} -n -f errorcodes.sed < ../calcerr.h >> $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 calc: usage
-	rm -f $@
-	cp usage $@
+	${RM} -f $@
+	${CP} usage $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 custom_cal: ../custom/CUSTOM_CAL
-	rm -f $@
-	cp ../custom/CUSTOM_CAL $@
+	${RM} -f $@
+	${CP} ../custom/CUSTOM_CAL $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 new_custom: ../custom/HOW_TO_ADD
-	rm -f $@
-	cp ../custom/HOW_TO_ADD $@
+	${RM} -f $@
+	${CP} ../custom/HOW_TO_ADD $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 copy: blkcpy
-	rm -f $@
-	cp blkcpy $@
+	${RM} -f $@
+	${CP} blkcpy $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 COPYING: ../COPYING
-	rm -f $@
-	cp ../COPYING $@
+	${RM} -f $@
+	${CP} ../COPYING $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 COPYING-LGPL: ../COPYING-LGPL
-	rm -f $@
-	cp ../COPYING-LGPL $@
+	${RM} -f $@
+	${CP} ../COPYING-LGPL $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 cscript: ../cscript/README
-	rm -f $@
-	cp ../cscript/README $@
+	${RM} -f $@
+	${CP} ../cscript/README $@
 	${CHMOD} 0444 $@
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 full: ${FULL_HELP_FILES} ${MAKE_FILE}
 	${Q} echo "forming full"
-	-${Q} rm -f $@
+	-${Q} ${RM} -f $@
 	-${Q} for i in ${FULL_HELP_FILES}; do \
 	    if [ Xintro != X"$$i" ]; then \
 		echo ""; \
 	    else \
-		true; \
+		${TRUE}; \
 	    fi; \
 	    if [ Xobj.file = X"$$i" ]; then \
 		j=obj; \
@@ -504,15 +512,15 @@ full: ${FULL_HELP_FILES} ${MAKE_FILE}
 	    echo "* $$j"; \
 	    echo "*************"; \
 	    echo ""; \
-	    cat $$i; \
+	    ${CAT} $$i; \
 	done > $@
 	${Q} echo "full formed"
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 # Singular files are the same files as their plural form.
@@ -520,18 +528,18 @@ full: ${FULL_HELP_FILES} ${MAKE_FILE}
 ${SINGULAR_FILES}: ${PLURAL_FILES}
 	${Q} for i in ${SINGULAR_FILES} /dev/null; do \
 	    if [ X"$$i" != X"/dev/null" ]; then \
-		echo "rm -f $${i}"; \
-		rm -f $${i}; \
-		echo "cp $${i}s $${i}"; \
-		cp $${i}s $${i}; \
+		echo "${RM} -f $${i}"; \
+		${RM} -f $${i}; \
+		echo "${CP} $${i}s $${i}"; \
+		${CP} $${i}s $${i}; \
 	    fi; \
 	done
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/SINGULAR_FILES =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/SINGULAR_FILES =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 # Form the builtin file
@@ -554,24 +562,24 @@ ${SINGULAR_FILES}: ${PLURAL_FILES}
 #
 builtin: builtin.top builtin.end ../func.c funclist.sed
 	${Q} echo "forming builtin help file"
-	-${Q} rm -f funclist.c
+	-${Q} ${RM} -f funclist.c
 	${Q} ${SED} -n -f funclist.sed ../func.c > funclist.c
-	-${Q} rm -f funclist.o funclist${EXT}
+	-${Q} ${RM} -f funclist.o funclist${EXT}
 	${Q} ${LCC} ${ICFLAGS} -DFUNCLIST -I/usr/include \
 	    -I.. funclist.c -c 2>/dev/null
 	${Q} ${LCC} ${ILDFLAGS} funclist.o -o funclist${EXT}
-	-${Q} rm -f builtin
-	${Q} cat builtin.top > builtin
+	-${Q} ${RM} -f builtin
+	${Q} ${CAT} builtin.top > builtin
 	${Q} ./funclist${EXT} | \
 	    ${SED} -e 's/^/	/' -e 's/[	 ][	 ]*$$//' >> builtin
-	${Q} cat builtin.end >> builtin
+	${Q} ${CAT} builtin.end >> builtin
 	${Q} echo "builtin help file formed"
 	-@if [ -z "${Q}" ]; then \
 	    echo ''; \
-	    echo '=-=-= skipping the cat of help/$@ =-=-='; \
+	    echo '=-=-= skipping the ${CAT} of help/$@ =-=-='; \
 	    echo ''; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 
 ##
@@ -606,21 +614,21 @@ calcliblist:
 # ignore this rule.
 #
 bsdi: all
-	rm -f obj
-	cp obj.file obj
+	${RM} -f obj
+	${CP} obj.file obj
 
 # These next rule help me form the ${DETAIL_HELP} makefile variables above.
 #
 detaillist:
 	${Q} -(echo "xxxxx"; \
 	   for i in ${DETAIL_HELP} /dev/null; do \
-	    if [ X"$$i" != X"/dev/null" ]; then \
-		if [ ! -f RCS/$$i,v ]; then \
-		    echo "WARNING: $$i not under RCS control" 1>&2; \
-		else \
-		    echo $$i; \
+		if [ X"$$i" != X"/dev/null" ]; then \
+		    if [ ! -f RCS/$$i,v ]; then \
+			echo "WARNING: $$i not under RCS control" 1>&2; \
+		    else \
+			echo $$i; \
+		    fi; \
 		fi; \
-	    fi; \
 	done | LANG=C ${SORT}) | ${FMT} -70 | \
 	    ${SED} -e '1s/xxxxx/DETAIL_HELP=/' -e '2,$$s/^/	/' \
 		   -e 's/$$/ \\/' -e '$$s/ \\$$//'
@@ -647,67 +655,67 @@ echo_inst_files:
 ##
 
 clean:
-	rm -f obj mkbuiltin funclist.c funclist.o funclist${EXT}
-	rm -f COPYING COPYING-LGPL
+	${RM} -f obj mkbuiltin funclist.c funclist.o funclist${EXT}
+	${RM} -f COPYING COPYING-LGPL
 
 clobber:
-	rm -f ${BLT_HELP_FILES} full .all calc
-	rm -f obj mkbuiltin funclist.c funclist.o funclist${EXT}
-	rm -f COPYING COPYING-LGPL
-	rm -f ${SINGULAR_FILES} ${DETAIL_CLONE}
+	${RM} -f ${BLT_HELP_FILES} full .all calc
+	${RM} -f obj mkbuiltin funclist.c funclist.o funclist${EXT}
+	${RM} -f COPYING COPYING-LGPL
+	${RM} -f ${SINGULAR_FILES} ${DETAIL_CLONE}
 
 # install everything
 #
 # NOTE: Keep the uninstall rule in reverse order to the install rule
 #
 install: all
-	-${Q} if [ ! -d $T${CALC_SHAREDIR} ]; then \
-	    echo mkdir $T${CALC_SHAREDIR}; \
-	    mkdir $T${CALC_SHAREDIR}; \
-	    if [ ! -d "$T${CALC_SHAREDIR}" ]; then \
-		echo mkdir -p "$T${CALC_SHAREDIR}"; \
-		mkdir -p "$T${CALC_SHAREDIR}"; \
+	-${Q} if [ ! -d ${T}${CALC_SHAREDIR} ]; then \
+	    echo ${MKDIR} ${T}${CALC_SHAREDIR}; \
+	    ${MKDIR} ${T}${CALC_SHAREDIR}; \
+	    if [ ! -d "${T}${CALC_SHAREDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${CALC_SHAREDIR}"; \
+		${MKDIR} -p "${T}${CALC_SHAREDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${CALC_SHAREDIR}; \
-	    ${CHMOD} 0755 $T${CALC_SHAREDIR}; \
+	    echo ${CHMOD} 0755 ${T}${CALC_SHAREDIR}; \
+	    ${CHMOD} 0755 ${T}${CALC_SHAREDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
-	-${Q} if [ ! -d $T${HELPDIR} ]; then \
-	    echo mkdir $T${HELPDIR}; \
-	    mkdir $T${HELPDIR}; \
-	    if [ ! -d "$T${HELPDIR}" ]; then \
-		echo mkdir -p "$T${HELPDIR}"; \
-		mkdir -p "$T${HELPDIR}"; \
+	-${Q} if [ ! -d ${T}${HELPDIR} ]; then \
+	    echo ${MKDIR} ${T}${HELPDIR}; \
+	    ${MKDIR} ${T}${HELPDIR}; \
+	    if [ ! -d "${T}${HELPDIR}" ]; then \
+		echo ${MKDIR} -p "${T}${HELPDIR}"; \
+		${MKDIR} -p "${T}${HELPDIR}"; \
 	    fi; \
-	    echo ${CHMOD} 0755 $T${HELPDIR}; \
-	    ${CHMOD} 0755 $T${HELPDIR}; \
+	    echo ${CHMOD} 0755 ${T}${HELPDIR}; \
+	    ${CHMOD} 0755 ${T}${HELPDIR}; \
 	else \
-	    true; \
+	    ${TRUE}; \
 	fi
 	-${Q} for i in ${STD_HELP_FILES} ${BLT_HELP_FILES} builtin \
 		  full ${DETAIL_HELP} ${SINGULAR_FILES} /dev/null; do \
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if ${CMP} -s $$i $T${HELPDIR}/$$i; then \
-		true; \
+	    if ${CMP} -s $$i ${T}${HELPDIR}/$$i; then \
+		${TRUE}; \
 	    else \
-		rm -f $T${HELPDIR}/$$i.new; \
-		cp -f $$i $T${HELPDIR}/$$i.new; \
-		${CHMOD} 0444 $T${HELPDIR}/$$i.new; \
-		mv -f $T${HELPDIR}/$$i.new $T${HELPDIR}/$$i; \
-		echo "installed $T${HELPDIR}/$$i"; \
+		${RM} -f ${T}${HELPDIR}/$$i.new; \
+		${CP} -f $$i ${T}${HELPDIR}/$$i.new; \
+		${CHMOD} 0444 ${T}${HELPDIR}/$$i.new; \
+		${MV} -f ${T}${HELPDIR}/$$i.new ${T}${HELPDIR}/$$i; \
+		echo "installed ${T}${HELPDIR}/$$i"; \
 	    fi; \
 	done
-	-${Q} if ${CMP} -s obj.file $T${HELPDIR}/obj; then \
-	    true; \
+	-${Q} if ${CMP} -s obj.file ${T}${HELPDIR}/obj; then \
+	    ${TRUE}; \
 	else \
-	    rm -f $T${HELPDIR}/obj.new; \
-	    cp -f obj.file $T${HELPDIR}/obj.new; \
-	    ${CHMOD} 0444 $T${HELPDIR}/obj.new; \
-	    mv -f $T${HELPDIR}/obj.new $T${HELPDIR}/obj; \
-	    echo "installed $T${HELPDIR}/obj"; \
+	    ${RM} -f ${T}${HELPDIR}/obj.new; \
+	    ${CP} -f obj.file ${T}${HELPDIR}/obj.new; \
+	    ${CHMOD} 0444 ${T}${HELPDIR}/obj.new; \
+	    ${MV} -f ${T}${HELPDIR}/obj.new ${T}${HELPDIR}/obj; \
+	    echo "installed ${T}${HELPDIR}/obj"; \
 	fi
 
 # Try to remove everything that was installed
@@ -715,12 +723,12 @@ install: all
 # NOTE: Keep the uninstall rule in reverse order to the install rule
 #
 uninstall:
-	-${Q} if [ -f "$T${HELPDIR}/obj" ]; then \
-	    rm -f "$T${HELPDIR}/obj"; \
-	    if [ -f "$T${HELPDIR}/obj" ]; then \
-		echo "cannot uninstall $T${HELPDIR}/obj"; \
+	-${Q} if [ -f "${T}${HELPDIR}/obj" ]; then \
+	    ${RM} -f "${T}${HELPDIR}/obj"; \
+	    if [ -f "${T}${HELPDIR}/obj" ]; then \
+		echo "cannot uninstall ${T}${HELPDIR}/obj"; \
 	    else \
-		echo "uninstalled $T${HELPDIR}/obj"; \
+		echo "uninstalled ${T}${HELPDIR}/obj"; \
 	    fi; \
 	fi
 	-${Q} for i in ${SINGULAR_FILES} ${DETAIL_HELP} full builtin \
@@ -728,18 +736,18 @@ uninstall:
 	    if [ "$$i" = "/dev/null" ]; then \
 		continue; \
 	    fi; \
-	    if [ -f "$T${HELPDIR}/$$i" ]; then \
-	    	rm -f "$T${HELPDIR}/$$i"; \
-		if [ -f "$T${HELPDIR}/$$i" ]; then \
-		   echo "cannot uninstall $T${HELPDIR}/$$i"; \
+	    if [ -f "${T}${HELPDIR}/$$i" ]; then \
+	    	${RM} -f "${T}${HELPDIR}/$$i"; \
+		if [ -f "${T}${HELPDIR}/$$i" ]; then \
+		   echo "cannot uninstall ${T}${HELPDIR}/$$i"; \
 		else \
-		   echo "uninstalled $T${HELPDIR}/$$i"; \
+		   echo "uninstalled ${T}${HELPDIR}/$$i"; \
 		fi; \
 	    fi; \
 	done
 	-${Q} for i in ${HELPDIR} ${CALC_SHAREDIR}; do \
-	    if [ -d "$T$$i" ]; then \
-		rmdir "$T$$i" 2>/dev/null; \
-		echo "cleaned up $T$$i"; \
+	    if [ -d "${T}$$i" ]; then \
+		${RMDIR} "${T}$$i" 2>/dev/null; \
+		echo "cleaned up ${T}$$i"; \
 	    fi; \
 	done
